parameters:
  skip: false

steps:
  - task: AzureCLI@1
    displayName: 'Integration Test Terraform Template'
    condition: not(coalesce(variables.SKIP_TESTS, ${{ parameters.skip }}))
    env:
      TF_VAR_remote_state_container: $(REMOTE_STATE_CONTAINER)
      TF_VAR_remote_state_account: $(REMOTE_STATE_ACCOUNT)
      TF_VAR_randomization_level: $(resourceNameIsolationLevel)
    inputs:
      azureSubscription: '$(SERVICE_CONNECTION_NAME)'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        #!/usr/bin/env bash
        set -euo pipefail

        export ARM_SUBSCRIPTION_ID=$(az account show --query id -otsv)
        export ARM_TENANT_ID=$tenantId
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_ACCESS_KEY=$(az storage account keys list --subscription "$ARM_SUBSCRIPTION_ID" --account-name "$TF_VAR_remote_state_account" --query "[0].value" --output tsv)

        cd "$ARTIFACT_ROOT"/"$TERRAFORM_TEMPLATE_PATH"

        # Setting the scripts to be run as executable
        chmod -fR 755 *.sh || true

        echo "TF_WORKSPACE_NAME: ${TF_WORKSPACE_NAME}"
        echo "TF_VAR_randomization_level: $TF_VAR_randomization_level"

        go test -v $(go list ./... | grep "$TERRAFORM_TEMPLATE_PATH" | grep "integration")
